import { AboutSlint, VerticalBox, GridBox, Button, HorizontalBox, ListView, Switch, Palette } from "std-widgets.slint";
component Button inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
    // height: txt.preferred-height * 1.33;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2 + (touch.pressed ? 2px : 0);
        y: (parent.height - self.height)/2 + (touch.pressed ? 1px : 0);
        color: touch.pressed ? #fff : #eee;
        font-size: 20px;
        horizontal-alignment: center;
    }
    touch := TouchArea { }
}

component ToggleSwitch inherits Rectangle {
    callback toggled;
    in-out property <string> text;
    in-out property <bool> checked;
    in-out property<bool> enabled <=> touch-area.enabled;
    height: 20px;
    horizontal-stretch: 0;
    vertical-stretch: 0;

    HorizontalLayout {
        spacing: 8px;
        indicator := Rectangle {
            width: 40px;
            border-width: 1px;
            border-radius: root.height / 2;
            border-color: root.checked ? Colors.white : Colors.black;            
            background: root.enabled ? (root.checked ? black : white)  : white;
            animate background { duration: 100ms; }

            bubble := Rectangle {
                width: root.height - 8px;
                height: bubble.width;
                border-radius: bubble.height / 2;
                y: 4px;
                x: 4px + self.a * (indicator.width - bubble.width - 8px);
                property <float> a: root.checked ? 1 : 0;
                Image {
                    width: 16px;
                    height: 16px;
                    source: root.checked ? @image-url("moon.png") : @image-url("sun.png");
                }
                animate a, background { duration: 200ms; easing: ease;}
            }
        }

        Text {
            min-width: max(100px, self.preferred-width);
            text: root.text;
            vertical-alignment: center;
            color: root.enabled ? black : gray;
        }

    }

    touch-area := TouchArea {
        width: root.width;
        height: root.height;
        clicked => {
            if (root.enabled) {
                root.checked = !root.checked;
                root.toggled();
            }
        }
    }
}

export component Calculator inherits Window {
    width: 300px;
    height: 400px;
    title: "Calculator";

    in-out property <string> display-text: "0";
    in-out property <string> operation-text: "";

    in-out property <bool> is-dark-theme: false;

    in-out property <bool> show-history: false;
    in-out property <[string]> history-list: [];

    in property <bool> memory-is-set: false;

    callback button-pressed(string);
    forward-focus: key-handler;
    key-handler := FocusScope {
        key-pressed(event) => {
            if (event.text == "0") {root.button-pressed("0");}
            else if (event.text == "1") { root.button-pressed("1"); }
            else if (event.text == "2") { root.button-pressed("2"); }
            else if (event.text == "3") { root.button-pressed("3"); }
            else if (event.text == "4") { root.button-pressed("4"); }
            else if (event.text == "5") { root.button-pressed("5"); }
            else if (event.text == "6") { root.button-pressed("6"); }
            else if (event.text == "7") { root.button-pressed("7"); }
            else if (event.text == "8") { root.button-pressed("8"); }
            else if (event.text == "9") { root.button-pressed("9"); }
            else if (event.text == ".") { root.button-pressed("."); }
            else if (event.text == "+") { root.button-pressed("+"); }
            else if (event.text == "-") { root.button-pressed("−"); }
            else if (event.text == "*") { root.button-pressed("x"); }
            else if (event.text == "/") { root.button-pressed("÷"); }
            else if (event.text == "c" || event.text == "C") { root.button-pressed("C"); }
            else if (event.text == "\n" || event.text == "=") { root.button-pressed("="); }
            else if (event.text == Key.Backspace) { root.button-pressed("←"); }
            else if (event.text == Key.Escape) { root.button-pressed("C"); }
            else if (event.text == Key.Delete) { root.button-pressed("CE"); }
            accept
        }   
    }

    VerticalBox {            
        spacing: 5px;
        padding: 5px;

        HorizontalBox {
            alignment: space-between;
            height: 24px;

            ToggleSwitch {
                toggled => {
                    Palette.color-scheme = self.checked ? ColorScheme.dark : ColorScheme.light;
                    is-dark-theme = !is-dark-theme;
                }
            }

            Text {
                text: "M";
                font-size: 14px;
                visible: root.memory-is-set;
                vertical-alignment: center;
            }

            history-button := TouchArea {
                width: 24px;
                height: 24px;
                Image {
                    source: @image-url("history.png");
                    colorize: is-dark-theme ? Colors.white : Colors.black;
                    width: parent.width;
                    height: parent.height;
                }
                clicked => { root.show-history = !root.show-history; }
            }
        }

        display_operation := TextInput{
            text: operation-text;
            read-only: true;
            font-size: 16px;
            horizontal-alignment: right;
            vertical-alignment: center;
            height: 30px;
            color: Colors.gray;
        }

        display := TextInput {
            text: display-text;
            read-only: true;
            font-size: 32px;
            horizontal-alignment: right;
            height: 60px;
        }

        GridBox {
            spacing: 5px;
            Row {
                Button { text: "MC"; clicked => { root.button-pressed(self.text) } background: #6c757d; }
                Button { text: "MR"; clicked => { root.button-pressed(self.text) } background: #6c757d; }
                Button { text: "M+"; clicked => { root.button-pressed(self.text) } background: #6c757d; }
                Button { text: "M-"; clicked => { root.button-pressed(self.text) } background: #6c757d; }
                Button { text: "MS"; clicked => { root.button-pressed(self.text) } background: #6c757d; }
            }
            Row {
                Button {text: "±";clicked => {root.button-pressed(self.text)};}
                Button {text: "CE";clicked => {root.button-pressed(self.text)};}
                Button {text: "C";clicked => {root.button-pressed(self.text)};}
                Button {text: "←";clicked => {root.button-pressed(self.text)}; colspan: 2;}
            }
            Row {
                Button {text: "7";clicked => {root.button-pressed(self.text)};}
                Button {text: "8";clicked => {root.button-pressed(self.text)};}
                Button {text: "9";clicked => {root.button-pressed(self.text)};}
                Button {text: "÷";clicked => {root.button-pressed(self.text)};colspan: 2;}
            }
            Row {
                Button {text: "4";clicked => {root.button-pressed(self.text)};}
                Button {text: "5";clicked => {root.button-pressed(self.text)};}
                Button {text: "6";clicked => {root.button-pressed(self.text)};}
                Button {text: "x";clicked => {root.button-pressed(self.text)};colspan: 2;}
            }
            Row {
                Button {text: "1";clicked => {root.button-pressed(self.text)};}
                Button {text: "2";clicked => {root.button-pressed(self.text)};}
                Button {text: "3";clicked => {root.button-pressed(self.text)};}
                Button {text: "−";clicked => {root.button-pressed(self.text)};colspan: 2;}
            }
            Row {
                Button {text: ".";clicked => {root.button-pressed(self.text)};}
                Button {text: "0";clicked => {root.button-pressed(self.text)};}
                Button {text: "=";clicked => {root.button-pressed(self.text)};}
                Button {text: "+";clicked => {root.button-pressed(self.text)};colspan: 2;}
            }
        }
    }

    hisotry_panel := Rectangle {
        visible: root.show-history;
        x:0;
        y:0;
        width: parent.width;
        height: parent.height;
        background: Colors.white;
        VerticalBox {
            padding: 10px;
            spacing: 10px;

            HorizontalBox {
                alignment: space-between;
                Text {
                    text: "History";
                    font-size: 20px;
                }
                TouchArea {
                    width: 24px;
                    height: 24px;
                    Text {
                        text: "X";
                        font-size: 20px;
                    }
                    clicked => {root.show-history = false;}
                }
            }

            Rectangle {
                border-radius: 4px;
                border-width: 1px;
                height: parent.height - 50px;
                ListView {
                    in-out property <[string]> model: root.history-list;
                    for item in model: Text {
                        text: item;
                        padding: 8px;
                    }
                }
            }

            
        }
    }
}
